language: python

python:
    - "2.7"

before_install:
    - sudo add-apt-repository -y ppa:shnatsel/dnscrypt
    - sudo apt-get update
    - sudo apt-get install -qq libsodium-dev

install:
    - "python setup.py install"
    - "pip install coverage coveralls pytest"

script: "coverage run --source=pseud setup.py test"

after_success:
    coveralls

notifications:
    email: false
