language: python

cache:
    apt
    pip

python:
    - "2.7"
    - "3.4"

before_install:
    - sudo add-apt-repository -y ppa:shnatsel/dnscrypt
    - sudo apt-get update && sudo apt-get install libsodium-dev
    - curl https://github.com/zeromq/zeromq4-1/archive/master.zip -L > zeromq4-1-master.zip
    - unzip zeromq4-1-master.zip
    - cd zeromq4-1-master && ./autogen.sh && ./configure && make -j && sudo make install && sudo ldconfig && cd -

install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -e .[Tornado,Gevent] futures pytest-pep8 pytest-cov coveralls; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install -e .[Tornado] pytest-pep8 pytest-cov coveralls; fi

script:
    - py.test --pep8 pseud tests --cov pseud

after_success:
    coveralls

notifications:
    email: false
