language: python

python:
    - "2.7"

install:
    - "python setup.py install"
    - "pip install coverage coveralls pytest"

script: "coverage run --source=pseud setup.py test"

after_success:
    coveralls

notifications:
    email: false
