language: python

python:
    - "2.7"
    - "3.4"

install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -e .[Tornado,Gevent] pytest-pep8 pytest-cov coveralls; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install -e .[Tornado] pytest-pep8 pytest-cov coveralls; fi

script:
    - py.test --pep8 --cov pseud

after_success:
    coveralls

notifications:
    email: false
